### ISSUE TITLE
[BUG] Usage of *= in attribute selector allows phishing-like attack

### ISSUE THREAD

**Issue by Night9072** [bdsources/sourcecheck#4]
By using *= in attribute selectors responsible for verifying urls, it is possible to craft a malicious URL that will have the verified color, weight, and check mark.

# Steps to reproduce
Send a url that looks like the following:
![image of "malicious" url](https://user-images.githubusercontent.com/51855329/59554987-00147b80-8fac-11e9-96b5-f9915daa205f.png)

# Proposed fix
Change the following
```css
[href*="://betterdiscord.net" i]
```
to
```css
[href^="http://betterdiscord.net" i]
[href^="https://betterdiscord.net" i]
```
(same applies to all other *= href attribute selectors)

**Comment by MasicoreLord** [comment]
Fixed bug @Night9072 closing issue now
https://github.com/bdsources/sourcecheck/commit/e58b7efdaa04a313d3fd4818c90f7d4428fa42fa
